version: "3.9"
services:
  pact-examples-docusaurus:
    build: .
    volumes:
      - ../output:/pact-examples/docs/output
      - ../README.md:/pact-examples/docs/pact-examples.md
    ports:
      - "3000:3000"
